# Generated by Django 2.2.4 on 2019-08-22 10:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pixlands', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='image',
            new_name='image_id',
        ),
    ]
