# Generated by Django 2.2.4 on 2019-08-23 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pixlands', '0002_auto_20190822_1304'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='likes',
            field=models.IntegerField(default=0, verbose_name='Like'),
        ),
    ]
