# Generated by Django 2.2.4 on 2019-08-23 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pixlands', '0003_image_likes'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='click_like',
            field=models.BooleanField(default=False, verbose_name=False),
            preserve_default=False,
        ),
    ]
