# Generated by Django 2.2.4 on 2019-08-23 14:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pixlands', '0004_image_click_like'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='click_like',
        ),
    ]
