# Generated by Django 2.2.4 on 2019-08-26 16:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pixlands', '0005_remove_image_click_like'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='likes',
        ),
    ]
