# Generated by Django 2.2.4 on 2019-08-26 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pixlands', '0006_remove_image_likes'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='likes',
            field=models.IntegerField(default=0, verbose_name='Like'),
        ),
    ]
