# Generated by Django 2.2.4 on 2019-08-26 16:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pixlands', '0007_image_likes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='likes',
        ),
    ]
