# Generated by Django 2.2.4 on 2019-08-30 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pixlands', '0010_auto_20190829_1630'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='public',
            field=models.BooleanField(default=True, verbose_name=False),
            preserve_default=False,
        ),
    ]
