# Generated by Django 2.2.4 on 2019-10-04 12:09

from django.db import migrations, models
import pixlands.models


class Migration(migrations.Migration):

    dependencies = [
        ('pixlands', '0012_remove_image_public'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='photos/%Y/%m/%d', validators=[pixlands.models.Image.validate_image]),
        ),
    ]
