# Generated by Django 2.2.4 on 2019-10-08 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pixlands', '0014_auto_20191007_1756'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='date_added',
            field=models.DateTimeField(),
        ),
    ]
