# Generated by Django 2.2.4 on 2019-10-11 12:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pixlands', '0021_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='comment',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='pixlands.Comment'),
        ),
        migrations.AddField(
            model_name='profile',
            name='image',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='pixlands.Image'),
        ),
        migrations.AddField(
            model_name='profile',
            name='like',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='pixlands.Like'),
        ),
        migrations.AddField(
            model_name='profile',
            name='topic',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='pixlands.Topic'),
        ),
    ]
