# Generated by Django 2.2.4 on 2019-10-14 11:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pixlands', '0022_auto_20191011_1544'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
