# Generated by Django 2.2.4 on 2019-10-14 12:12

from django.db import migrations, models
import pixlands.models


class Migration(migrations.Migration):

    dependencies = [
        ('pixlands', '0023_delete_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profilepic',
            name='image',
            field=models.ImageField(blank=True, default='/static/user.svg', upload_to=pixlands.models.ProfilePic.user_directory_path),
        ),
    ]
