# Generated by Django 2.2.4 on 2019-10-14 13:45

from django.db import migrations, models
import pixlands.models


class Migration(migrations.Migration):

    dependencies = [
        ('pixlands', '0025_auto_20191014_1517'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profilepic',
            name='image',
            field=models.ImageField(blank=True, default='static/user.svg', upload_to=pixlands.models.ProfilePic.user_directory_path),
        ),
    ]
