# Generated by Django 2.2.4 on 2019-10-17 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pixlands', '0028_auto_20191015_1624'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topic',
            name='text',
            field=models.CharField(max_length=50),
        ),
    ]
