# Generated by Django 2.2.3 on 2020-03-04 15:21

from django.db import migrations, models
import pixlands.models


class Migration(migrations.Migration):

    dependencies = [
        ('pixlands', '0029_auto_20191017_1746'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(upload_to='photos/%Y/%m/%d', validators=[pixlands.models.Image.validate_image]),
        ),
    ]
