# Generated by Django 3.0.4 on 2020-03-13 13:07

from django.db import migrations, models
import pixlands.models


class Migration(migrations.Migration):

    dependencies = [
        ('pixlands', '0030_auto_20200304_1821'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(upload_to='media/photos/%Y/%m/%d', validators=[pixlands.models.Image.validate_image]),
        ),
    ]
